### PR TITLE
Added broadcast support to ModbusTcpClient

### PR DESCRIPTION
**Pull request by mile-bkoos**
The ModbusTcpClient missed the support for broadcast messages.
I copied the two code parts from the ModbusRtuClient into the ModbusTcpClient.

### CODE REVIEW

**Comment by Apollo3zehn** [comment]
Hi, thanks for your contribution! I am quite slow right now, I know. I don't know yet when I will be able to review your changes and I need to be careful with such kind of changes as this project became more popular recently (which means I need to check the specification against your changes).

I will do it eventually but please bear with me :-)

**Comment by Apollo3zehn** [comment]
I wanted to merge your changes but it causes many tests to fail.

In the spec (https://www.modbus.org/docs/Modbus_Messaging_Implementation_Guide_V1_0b.pdf, p.23) I read about the broadcast support and unit identifiers and found this:

grafik
 
My understanding is that when talking to Modbus RTU devices, a unit identifier of `0` means broadcast. And when talking to Modbus TCP devices, a unit identifier of `0` is a normal address.

Since the Modbus TCP client cannot distinguish between a regular Modbus TCP server and a Modbus TCP/RTU bridge I am not sure how to implement this properly.

The unit tests fail because they use unit identifier `0` to talk to the server and the newly introduced broadcast checks cause exceptions like `Invalid use of broadcast: Unit identifier '0' can only be used for write operations.`.

Do you have an idea how to implement this properly?

**Comment by mile-bkoos** [comment]
We use modbus gateways that behave transparently. These translate the modbus RTU connection to TCP/IP. In this case, the unit identifier behaves in exactly the same way as with an RTU connection and the broadcast is also identical. We are already using this successfully with the adjustments i made in this pull request.

A distinction may have to be made here as to whether a connection is established with a native modbus TCP device or with a gateway.

We use various modbus gateways - e.g. the Advantech EKI-1211 (https://www.advantech.com/en/products/db72f61c-801b-4e61-8863-5d418f01b6e9/eki-1211/mod_a4b66858-17a7-4b3f-bbfe-ac86409cdc61)

**Comment by mile-bkoos** [comment]
First of all sorry for not running the unit tests before creating the pull requests.
In fact we are using it to connect to a modbus RTU gateway / bridge. I added a new flag `RTUGatewayMode` so that the special handling for the unit identifier 0 only triggers if the flag is set to true :)

**Comment by endrelovas** [comment]
Guys how is this going now? Is it getting merged?

**Comment by mile-bkoos** [comment]
With the latest release "ModbusRtuOverTcpClient.cs" was implemented so this PR is no longer needed.

**Comment by Apollo3zehn** [comment]
Thanks anyway for your efforts. I am glad the other implementation helps you as well.

**Pull request closed without merging**
