### PR TITLE
#99 Implement ModbusRtuOverTcpClient.cs

### PR DESCRIPTION
**Pull request by schotime**
I've done a very quick implementation here, but I haven't had time to test it against a real device which I'm hoping to do tomorrow, and so I'll leave this PR here for now and come when I have some details on how it went.

### CODE REVIEW

**Comment by schotime** [comment]
Ok, I have had this running for the last 12 hours, and it seems to be fairly reliable. You can have a look.

**Comment by omfarcel** [comment]
Hello friends, thank you both. I quickly read the data and didn't encounter any issues."

**Comment by Apollo3zehn** [comment]
Thank you :-)

**Comment by schotime** [comment]
@Apollo3zehn Did a release get done for this?

**Comment by Apollo3zehn** [comment]
Sorry I planned to be quicker with a v6 release but I am not so there is now v5.3.0 which includes your changes :-)

**Comment by schotime** [comment]
Thanks. I know that feeling!
I'm implementing the server part in a project a project this month,  so looking forward to that.

**Pull request merged**
